### ISSUE TITLE
same issue as https://github.com/PKISolutions/PSPKI/issues/93 , unable to connect with remote CA

### ISSUE THREAD

**Issue by chris-we-1** [PKISolutions/PSPKI#107]
hi there,

first, i love the pspki project. 2nd, i'm automating cert requests for a customer, where i stumbled on the same issue as https://github.com/PKISolutions/PSPKI/issues/93. The suggestion to try with the vnext build did not work. anything i can do to get a more uptodate/verified pspki version? another branch maybe? (i used the vnext branch to testdrive this after i got the error).

thanks for any advise.

**Comment by chris-we-1** [comment]
![Capture](https://user-images.githubusercontent.com/67639107/86125048-53d10480-badc-11ea-9342-7fd893ba64b7.PNG)

**Comment by Crypt32** [comment]
`localhost` for `-ComputerName` parameter is not valid name. It will expect a CA with exact name called `localhost`, which is a special loopback name. For localhost just omit this parameter.

**Comment by chris-we-1** [comment]
All of these work locally but not over pssession …same error… so any guess why this happens?

[cid:image001.jpg@01D650A9.55D55DF0]

Mvg,

Chris Sauquillo

**Comment by Crypt32** [comment]
PSPKI doesn't support PS Remoting, because most commands do external calls and they will fail due to "double hop" problem. It requires to enable remote server trusted for credential delegation, which is not enabled by default and enabling this may cause security risks.

I didn't notice that you are running the command in remote session. In this case, error message is expected and by design.

**Comment by chris-we-1** [comment]
Alright, thx for clearing this up. Have a good one

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
