### ISSUE TITLE
PSPKI not .NET Core based, thus can't be used natively in PowerShell 7.

### ISSUE THREAD

**Issue by doctordns** [PKISolutions/PSPKI#137]
Two things:
1. It appears that the PSPKI module is not supported with .NET Core, meaning it is not supported natively in PowerShell 7/7.1/7.2. Can that get fixed?
2. I would love to see a worked example of
- installing a CA - a single CA
- Installing a CA - including an offline root and subordinate issuing CA (2-level)
- Configuring a Server to get and use a cert (eg for IIS SSL). 
Regarding number 1 - I would actually be willing to pay for a worked example that I can point to for my next PowerShell book. It would really help my readers.

**Comment by Crypt32** [comment]
> It appears that the PSPKI module is not supported with .NET Core, meaning it is not supported natively in PowerShell 7/7.1/7.2. Can that get fixed?

.NET Core can use older .NET Framework libraries, so I don't see why you can't use PSPKI in PowerShell 7. There is little reason to compile under .NET Core since this module is Windows-only (due to a heavy dependency on COM/DCOM) and there are limitations on the use of .NET Core in customer environments.

> installing a CA - a single CA
> Installing a CA - including an offline root and subordinate issuing CA (2-level)

these tasks are available on discontinued Windows Server 2008 R2 systems only. Starting with Windows Server 2012 and newer, this functionality is implemented in Microsoft built-in ADCSDeployment module which is recommended way to install ADCS CA: https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcscertificationauthority?view=win10-ps. If you have specific requirement, I can help you with code samples.
