### ISSUE TITLE
Add-CertificateTemplate missing

### ISSUE THREAD

**Issue by georg-x** [PKISolutions/PSPKI#138]
It seems not a simple task to create new certificate templates via script.

I see this functions in the documentation to fetch or remove templates from AD:
- Get-CertificateTemplate
- Remove-CertificateTemplate

But an Add-CertificateTemplate doesn't exist.

This issue can be seen as either feature request, or as documentation, why such a function doesn't exist.

Such a thing was suggested here:
https://social.technet.microsoft.com/Forums/lync/en-US/347acc93-8352-4535-ab1a-23ebd49eea22/duplicate-certificate-template-edit-and-publish-it?forum=winserverpowershell

**Comment by Crypt32** [comment]
Currently, there are no plans to support automated certificate template creation, nor modification. I had a support case with Microsoft and I was told that they do not support template creation/modification outside of Certificate Templates MMC snap-in, because MMC handles configuration restrictions and mutually exclusive settings. An attempt to reverse-engineer existing behavior and re-implement in code seems to be a fragile solution and will require a lot of efforts to test every single setting. A quote from Windows PKI team engineer:

> That’s correct, we donot provide a method to create a template from scratch. (There are inherent inter-dependencies between various template attributes which are enforced via visual clues and complex logic from the template snapin.)
> 
> The scenario supported is the developer installs DC, CA, Enrollment Service and Enrollment Policy service roles. Duplicates a template via the template snapin, modifies the properties on the duplicated template, enables the template on the CA and enables the enrollment service to point to the CA.


If you apply the code from referenced link, you are risking to put yourself into unsupported configuration. Everything we ship in PSPKI module is supported by Microsoft.

**Comment by georg-x** [comment]
Thank you for clearing that up and also for the evaluation on the link!

**Comment by Crypt32** [comment]
What we can support is export-import process for certificate templates. That is, you create and configure certificate template using Certificate Templates MMC snap-in and then import exported data back to same or different AD forest. But we still won't support exported data modification outside of Certificate Templates MMC.

**Comment by Crypt32** [comment]
I'm closing this issue as resolved. If you have other questions, please start new thread.
