### ISSUE TITLE
request: parameter to target a forest with Get-CertificateTemplate and related cmdlets

### ISSUE THREAD

**Issue by jordanmills** [PKISolutions/PSPKI#166]
It looks like Get-CertificateTemplate has no way to specify what forest to use for queries.  In a situation where I'm using a user/computer from forest A, which has a trust with forest B, but has separate PKI resources, and want to alter a template ACL in forest B, there is no way to target forest B.  The specific kind of use case here is an ESAE/red forest, where an admin account would exist in forest A and use a computer joined to forest A (or maybe forest B) to manage templates (and other resources) in forest B.  

Running Connect-CA works fine in this case, and allows me to connect to a CA in forest B.  So at least some of the interfaces work.

Thanks

**Comment by Crypt32** [comment]
Cross-forest environments are not supported by PSPKI. Although `Connect-CA` does work in cross-forest scenario it is not officially supported and may have side effects, because some information about CA is retrieved from AD and local forest is assumed. That is, if you call `Get-CATemplate` against CA in remote forest, it will immediately fail, because it will read templates from local forest, not the forest CA belongs to.

Cross-forest support is a big subject with its own limitations. I will put this request on hold for future consideration.

**Comment by jordanmills** [comment]
Thanks.  I do understand that there can be some major issues working with enterprise (windows domain-joined) PKI cross-forest.  For cases like this, I could definitely make it work if with the condition that all computers involved be in the same forest (user from forest A signed in to computer in forest B working with templates in forest B).  

I also want to test it in a case where forest A has appropriate AIA, CRL, and CDP objects for forest B.  If the issues are only around what is returned by lookups, then that might work.

Either way, the module provides great value.  Thanks for all the work you put into it.
