### ISSUE TITLE
Get-EnterprisePKIHealthStatus object to JSON

### ISSUE THREAD

**Issue by bencoremans** [PKISolutions/PSPKI#169]
I have a question about converting the PowerShell object from Get-EnterprisePKIHealthStatus to JSON with ConvertTo-Json for later use.
When I do this the values like Status, ChainStatus, UrlType will change to integers in the JSON, while in the object the values are like Ok, Expiring and for UrlType Certificate, Crl.

Do you know how I can manage to get the text in the JSON?
Or is there a way to convert the integers back to the text values? Convert table?

Thanks in advance.
Ben

**Comment by Crypt32** [comment]
> When I do this the values like Status, ChainStatus, UrlType will change to integers in the JSON, while in the object the values are like Ok, Expiring and for UrlType Certificate, Crl.

this is expected, because these "text" values are enumerations which are integral values. Therefore you have to deserialize them into properties of same enumeration type. Deserialization into anonymous (like `PSCustomObject`) looses this mapping.

What you have to do is to create a 1:1 mapping between your types and types defined in script with writable properties and without methods.

**Comment by bencoremans** [comment]
Thank you for suggestion. I managed to create a JSON with the text values.
