### ISSUE TITLE
remote execution using "Enter-PSSession"

### ISSUE THREAD

**Issue by shivarajmulimani** [PKISolutions/PSPKI#174]
Can we execute `Get-CertificationAuthority` and `Get-CertificateTemplate` command on remote machine using `Enter-PSSession`.
if not is there any alternative way collect  templates from remote windows machine.

**Comment by Crypt32** [comment]
> Can we execute Get-CertificationAuthority and Get-CertificateTemplate command on remote machine using Enter-PSSession.

no, it is not supported, because it will cause double-hop authentication problems. CA-related commands (`Connect-CA` and `Get-CA`) allow you to specify remote CA server name you can connect from local computer.

Certificate templates are installed in AD, Configuration Naming Context which is replicated across all domain controllers in the forest, thus you can use any AD-joined machine to query for installed in AD templates.
