### ISSUE TITLE
Cmdlets take too long for execution

### ISSUE THREAD

**Issue by alsanma** [PKISolutions/PSPKI#46]
Hi Vadims, 

I'm using cmdlet get-ca and it seems to take several minutes to finish execution. It takes around 20-25 minutes. 

I checked this cmdlet and I realized it is using this class/method to get CA object "[PKI.CertificateServices.CertificateAuthority]::EnumEnterpriseCAs". 

I tried two different Enterprise CAs with same hardware and OS (ws2012R2), and one of them is finishing in just 1 second but the other one seems to get stucked. 

Do you know if it takes into account CA database size, crl size, remote registry, or any other component from CA that could be the reason? configuration between CAs are similar (ocsp, aia/cdp extensions,...).

I really appreciate you help. 

Thanks.

**Comment by Jay-Armstrong** [comment]
I am having the same problem. On one server the Get-CertificationAuthority takes about 8 seconds to complete, on another it is taking 50+ minutes.

This has started within the past 2 months based on the last time I worked against the server. What protocols are used to do the connections?

**Comment by Jay-Armstrong** [comment]
That is exactly what I needed. I am sure it is an issue on the server (probably a patch that didn't get installed properly), now I where to dig deeper. Thanks!

**Comment by Jay-Armstrong** [comment]
When running Connect-CertificationAuthority -ComputerName server.fqdn -Verbose -ErrorAction "Stop" while logged onto the server locally:

PS>TerminatingError(New-Object): "Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)""
>> TerminatingError(): "Error connecting to server.fqdn"
>> TerminatingError(): "Error connecting to server.fqdn"

Any idea what is happening?

**Comment by Crypt32** [comment]
Does the command succeed when you call it without `-ErrorAction` parameter?

Also, post stacktrace after exception:
```
$error[0].Exception.InnerException.StackTrace
```

**Comment by Jay-Armstrong** [comment]
TerminatingError(New-Object): "Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)""
>> TerminatingError(New-Object): "Exception calling ".ctor" with "1" argument(s): "CCertConfig::GetField: The parameter is incorrect. 0x80070057 (WIN32: 87 ERROR_INVALID_PARAMETER)""
   at CERTCLILib.CCertConfigClass.GetField(String strFieldName)
   at PKI.CertificateServices.CertificateAuthority.get_ds()
   at PKI.CertificateServices.CertificateAuthority.initialize()
>> TerminatingError(): "Error connecting to server.fqdn"

**Comment by Crypt32** [comment]
First of all: it seems that you are not using the most recent version of PSPKI module.  Based on your stack trace, I can say that you are using version which is at least 2yrs old. Generally, I support only last two versions. I would suggest to get the latest version from PS gallery on offline zip package. All information can be found on main page.

Anyway, this error proves that you have some broken or corrupt CA registration entries in Active Directory. Can you review contents of the following DS container:

```
CN=Enrollment Services, CN=Public Key Services, CN=Services, {ConfigurationNamingContext}
```

**Comment by Jay-Armstrong** [comment]
I have 3.2.5 on my server, 3.3.0 is available, but I cannot install it on my server till the issue is gone due to infrastructure controls. 

Interestingly the command completes without error when I run it from another machine. Still takes 45 minutes, but it completes without error.

**Comment by Crypt32** [comment]
What about DS entries I asked earlier?

p.s. I'm afraid, but there is no chance that you will get fix without upgrading to the most recent module version.

**Comment by Crypt32** [comment]
Closing as non-constructive. I asked several times about DS objects and get no response. Once you can proceed with this issue, just reply to this thread.

**Comment by Jay-Armstrong** [comment]
Yes, I am able to enumerate the item
distinguishedName  : CN=ADICA v2,CN=Enrollment Services,CN=Public Key
                     Services,CN=Services,CN=Configuration,DC=,DC=,DC=com
name               : ADICA v2
objectClass        : pKIEnrollmentService

**Comment by Jay-Armstrong** [comment]
Holiday weekend here in the States, sorry for the slow reply.

**Comment by Jay-Armstrong** [comment]
I don't think having 3.3.0 on the server will change the issue. 

I am using pspki for remote management from an automation server, and that server does have 3.3.0 with the 45+ minute Connect-CertificationAuthority run time. 

I was trying to run it locally to see if it exhibited the same problem to rule out network issues. Since the problem exists on one of two servers, using both in 3.2.5 and 3.3.0, I don't believe it to be an issue with pspki but something on the server.

We did a delegation on our CAs and in Active Directory for a PKI admin group early this year, but haven't have a problem with any of the scripts till now. The last time I used pspki against the server was in June, and there were no issues then. I have another script using certreq against the CA that has no issues.

The Certificate authority mmc is fine, no problems there.

**Comment by Crypt32** [comment]
What type is the CA you are trying to connect to? Standalone, Enterprise?

**Comment by Jay-Armstrong** [comment]
Enterprise CA. The standalone has no problems.

**Comment by Crypt32** [comment]
I assume that you have only single Enterprise CA in your AD forest? If so, then can you confirm that your CA entry in `CN=Enrollment Services` DS container has `dnsHostName` attribute and its value is not null or empty and points to the right server name?

**Comment by Jay-Armstrong** [comment]
Correct, one integrated Certificate Authority, dNSHostName is present and correct. DNS is correct.

**Comment by Crypt32** [comment]
Ok, can you execute the following commands on a computer where the command throws exception:

```PowerShell
$CertConfig = new-object -com certificateauthority.config
Write-Host "Count: " $CertConfig.Reset(0)
while ($CertConfig.Next() -ge 0) {
    $flags = $CertConfig.GetField("flags")
    $server = $CertConfig.GetField("server")
    Write-Host "Flags: $flags, server: $server"
}
```
And post the output.

**Comment by Jay-Armstrong** [comment]
Count:  1
Flags: 13, server: server.fqdn

**Comment by Crypt32** [comment]
Then the stack trace you provided in https://github.com/Crypt32/PSPKI/issues/46#issuecomment-417522164 is not correct.

**Comment by Jay-Armstrong** [comment]
Not sure what that indicates as it is the error that was returned.

**Comment by Crypt32** [comment]
Then there is missing something. You must run this PowerShell code in exact scenario when module throws error: same machine and same user account.

**Comment by Jay-Armstrong** [comment]
The only difference is this was executed from a scheduled task instead of interactive:

Count:  1
Flags: 12, server: server.fqdn

**Comment by Crypt32** [comment]
Make sure that "enable highest priveleges" checkbox is enabled in scheduled task.

**Comment by Jay-Armstrong** [comment]
Ok, I have an update.

I installed 3.3.0 on the server and am running the task as system. Concurrently I am running the commands remotely using a CA administrative account.

The Connect-CertificationAuthority completed without error, but it still takes >45 minutes to complete.

Now, when I get to the following command I get a large number of errors:
Get-IssuedRequest -CA $caADICA -Filter "CertificateTemplate -eq $template" -properties upn, certificatetemplate, DistinguishedName

```
Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."
At C:\Program Files\WindowsPowerShell\Modules\PSPKI\3.3.0.0\Server\Get-RequestRow.ps1:121 char:13
+             $Row.Properties.Add($colName, $colVal)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
Exception calling "Add" with "2" argument(s): "An item with the same key has
already been added."
At C:\Program
Files\WindowsPowerShell\Modules\PSPKI\3.3.0.0\Server\Get-RequestRow.ps1:121
char:13
+             $Row.Properties.Add($colName, $colVal)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException


```
The call does return the records once the errors complete. This happened on both the server as system and using my CA administrative account when running remote.

**Comment by Jay-Armstrong** [comment]
Both as a task and when running interactively. Remote or local does not change the issue.

**Comment by Crypt32** [comment]
If Connect-CertificationAuthority now executes without exceptions, you will have to profile method chain call to determine which code line (or lines) hangs. You will have to download sources, compile them and perform code profiling/debugging. There is nothing I can suggest, because I can't repro this issue.

**Comment by Jay-Armstrong** [comment]
Ok, engaging MS. I'll let you know what is found.

**Comment by PatrickOnGit** [comment]
Hello Vadims

I had similar issues as Jay-Armstrong when using `Connect-CertificationAuthority`.

The problem I have is, one of the CAs at the customer is used only for webenrollment (lets call it WebCA) and not exposed to the intranet. The third party WebRA is located in the same DMZ like network as the "WebCA" and uses RPC to connect.
The WebRA can be reached from the Intrant.
The WebCA can't be reached.

The WebRA is configured as normal Enrollment CA with all it's data in Active Directory. It can therefore be discovered using CertificateAuthority.Config com object.

From how I understand your code, Connect-CertificationAuthority is doing the following:

1. calling `PKI.CertificateServices.CertificateAuthority`.
1.1 Verify if the server is online within `PKI.CertificateServices.CertificateAuthority`, using `RegistryOnline = CryptoRegistry.Ping(computerName);`
1.1.1 Tries to open the registry `RegistryKey key = RegistryKey.OpenRemoteBaseKey(RegistryHive.LocalMachine, computerName);`.
	-> Opening the registry over the network takes quite some time. Especially if it fails due to some network / firewall issues.
1.2 Even if the remote registry fails, testing if the CA is online `IsAccessible = Ping(computerName);`
1.3 Try to find server in AD `lookInDs(computerName);`
1.3.1 Verify if client reaches any DC `ActiveDirectory.Ping()`
1.3.1.1 By getting its current domain `Domain.GetCurrentDomain().Name`
1.3.2 When a host name is used, it is changed by adding current domain name
	-> This is a objectionable assumption and only valid in single domain forest! In a multidomain forest it cannot be assumed that the current logged on account returns the same domain name as the CA is using.
	-> If the account used to administer / access the CA, the current domain is the child domain but the the CA might be located in the root domain.
	-> Better option is search AD configuration context for enrollment server or global catalog for server name or use DNS to resolve hostname
1.3.3 Loop thru each FQDN found in _certConfig.
1.3.4 Building CA configuration information 
	Now it gets a bit complicated, but depending on previous tests, you search again AD or get infos directly from CA.
	
Without a server name this process happens against each CA defined in AD.
Using servername parameter it retrieves a single server but does the same process. 

The problem is, the process requires multiple connections against each server, even before knowing if the server does exist in AD or the name can be resolved.
This leads to slow performance.

Based on above description (and I'm not saying that my quick analysis is correct), I think the PSPKI module assumes / require the following to work correct:

- The current user has at least auditor rights in order to retrieve the CA certificate (Using CertAdmin interface instead of CertificateAuthority.Request)
- The current logged on user is in the same domain as the CA (appending current domain dns name to host name in lookInDs Method of CertificateAuthority object)
- The current logged on user has local admin rights to the CA (trying to access remote registry)
- It is running in a single domain forest (using current domain, LDAP and serverless bindings)

I think there are some quick fixes to improve the performance and some changes that requires some design changes.

I would be happy to support you if you are interested.

Kind regards
Patrick

**Comment by Crypt32** [comment]
First of all, thanks for joining to discussion, because it helps in code review and issue detection!

> -> Opening the registry over the network takes quite some time. Especially if it fails due to some network / firewall issues.

yes, it is correct. You may expect delays (not very big) when remote registry or RPC/DCOM is not available for any reason. The only reliable way to check them is to attempt to connect and look for response. If response fails (timeout, or whatever other reason), I mark this access interface as unavailable.

> -> This is a objectionable assumption and only valid in single domain forest! In a multidomain forest it cannot be assumed that the current logged on account returns the same domain name as the CA is using.
> -> If the account used to administer / access the CA, the current domain is the child domain but the the CA might be located in the root domain.
> -> Better option is search AD configuration context for enrollment server or global catalog for server name or use DNS to resolve hostname
> 1.3.3 Loop thr
u each FQDN found in _certConfig.
> 1.3.4 Building CA configuration information
> Now it gets a bit complicated, but depending on previous tests, you search again AD or get infos directly from CA.

I can't agree with this part. If you take a look at this line: https://github.com/Crypt32/pkix.net/blob/5b0217f1b32897b21ce831ce2ca22c1a7cf912c4/PKI/CertificateServices/CertificateAuthority.cs#L162

I'm appending current domain name only when input name doesn't include dot character. Name without dots is short or NetBIOS name. So when short/NetBIOS name is specified in parameters, we expect to find it in the current domain. In fact, it is what DNS client does in domain environment by deault:
![capture](https://user-images.githubusercontent.com/6384119/47030297-20b6d800-d176-11e8-9647-c1a5399720fe.png)

So, I think it is ok to use current domain when no explicit domain (in FQDN form) is specified. When name is specified in FQDN form, I use provided name to perform host search. Eventually, I will end up in right domain.

> Without a server name this process happens against each CA defined in AD.

can you clarify what do you mean? There is no constructor that would accept null or empty server name. `Connect-CertificationAuthority` defaults to local computer when server name is not specified. Another story is with `Get-CertificationAuthority`, which performs these steps for each CA found in Active Directory. It is what everyone would expect, since this cmdlet returns CAs registered in Active Directory.

> The problem is, the process requires multiple connections against each server, even before knowing if the server does exist in AD or the name can be resolved.

This behavior was designed this way to support Standalone CAs which are not registered in AD as enrollment service. As the result, I have to attempt to connect to specified host even if it is not registered in AD.
I'm not sure if there is a way to reduce the amount of connections I'm doing right now. Anyway, in lab I keep decommissioned CA record in AD and combined delays from all connections barely exceed 1-2 minutes. It is acceptable delay unless there are better ways to determine if specified host exist, is CA and can be connected to.

> I think there are some quick fixes to improve the performance and some changes that requires some design changes.

I'm open to any good ideas.

**Comment by PatrickOnGit** [comment]
Hello Vadmis

Thank you for taking time to provide feedback on my comments.

> [Patrick] -> Opening the registry over the network takes quite some time. Especially if it fails due to some network / firewall issues.
> [Vadims] yes, it is correct. You may expect delays (not very big) when remote registry or RPC/DCOM is not available for any reason. The only reliable way to check them is to attempt to connect and look for response. If response fails (timeout, or whatever other reason), I mark this access interface as unavailable.

True, and you return this information in your `PKI.CertificateServices.CertificateAuthority` object. 
But you explicitly state in your script (running on offline, non domain joined CA or computer) "Non-domain environments are not supported." We could therefore consider that CAs in scope must be registered in AD, one way or another, even if not registered as Enrollment CA. Therefore if a server does not exist in AD, (has a computer object in AD and, in case it is really a CA, has an PKI-Enrollment-Service object registered in AD)  you don't even have to try to test if registry is online or if CA is accessible. 
Trying to reach a specific CA, short delays are not an issue. Looping through all CA are.

So why not considering changing the order of events? 

1. First query AD for enrollment server
2. Then test the interfaces

> I can't agree with this part. If you take a look at this line: https://github.com/Crypt32/pkix.net/blob/5b0217f1b32897b21ce831ce2ca22c1a7cf912c4/PKI/CertificateServices/CertificateAuthority.cs#L162

> So when short/NetBIOS name is specified in parameters, we expect to find it in the current domain. In fact, it is what DNS client does in domain environment by deault

This is not the same, you compare apple with pies.
DNS client is adding **machines** connection specific suffix and is also using devolution. In case you are in a child domain, the following happens:
Netbios name to resolve: CA1
Primary Suffix: CHILD1.ROOT.COM
1. try lookup CA1.CHILD1.ROOT.COM
if failed
2. try lookup CA1.ROOT.COM
So you get the name of CA1 even if your client is member of the child domain.
If you are using a connection specific suffix, DNS resolver even tries that.
You may use nslookup interactively and use "set db2" to get all the lookups when trying to resolve a hostname
https://searchwindowsserver.techtarget.com/tip/How-DNS-devolution-works-in-Windows-Server-2008-R2

But what you are doing is adding the current **user** domain suffix by using 'directoryservices.activedirectory.domain.getcurrentdomain'.
https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.activedirectory.domain.getcurrentdomain
Therefore, if the CA admin/operator is member of the child domain, using hostname will never return a CA.

> Without a server name this process happens against each CA defined in AD.

OK, what I mean is exactly what you describe. Using Get-CertificationAuthority without parameter lists all CAs found in AD. So if AD contains lots of dead entries, it takes quite some time to return. An option would be to add a new parameter "-NoIsOnlineCheck". You could then still return all information stored in AD like the CA certificates. You may not get CRLs as you need to get the CDP stored in a certificate (ie CAExchangeCert) or from the CA itself as you already do (if it is online....)

I attached some LDAP logs. So certutil config only returns CA registered as enrollment server.
But you are right, to test an interface you need to connect to it. And only because one interface is down (not accessable), doesn't mean the other interface is down as well.
[Testing_Get-CertificationAuthority.txt](https://github.com/Crypt32/PSPKI/files/2486464/Testing_Get-CertificationAuthority.txt)

BTW: what makes RPC horrible slow is when port 135 is accessible but the RPC interface itself is not. This happens often when using bad FW configurations. But that is not your problem.

I also attached my version of Get-CertificationAuthority based on an older PSPKI implementation that did not use the DLLs.
[Get-CertificationAuthority.ps1.txt](https://github.com/Crypt32/PSPKI/files/2486713/Get-CertificationAuthority.ps1.txt)

**Comment by Crypt32** [comment]
Let me clarify some points.
1. We have two cmdlets, `Get-CertificationAuthority` and `Connect-CertificationAuthority`.
2. `Get-CertificationAuthority` is supported only in Active Directory and retrieves only Enterprise CAs registered in AD as enrollment servers.
2.1. Enterprise CA lookup starts with `ICertConfig` where I retrieve server's FQDN. There is no issue with short names, because they are not used.
2.2. `Get-CertificationAuthority` returns an array of CAs.
3. `Connect-CertificationAuthority` is intended to connect explicitly specified CA, whether it is Enterprise or Standalone CA.
3.1. When calling `lookInDs`, we check if server name is provided in NetBIOS of FQDN form.
3.2. If it is NetBIOS name, we append current domain name to it in order to get FQDN, then pass this name to `ICertConfig`. It is important to understand that `ICertConfig` may not return any matching records (for Standalone CAs), so I will have to deal with host name provided in parameters.
3.3. `Connect-CertificationAuthority` returns only single CA instance.

From what I understand, you suggest to not append current domain name, leave NetBIOS as is and let DNS client to perform host lookup. Is it correct? Ok, I can do it. However, `ICertConfig` may return multiple servers with same host name in different domains. What should I return in this case? Which CA?

> Therefore, if the CA admin/operator is member of the child domain, using hostname will never return a CA.

I got your point. Yes, my intention was to add *machine* domain suffix to perform lookup, regardless of logged user's domain. 

> So if AD contains lots of dead entries, it takes quite some time to return. An option would be to add a new parameter "-NoIsOnlineCheck"

I don't think if it is a good idea. Basically, if you have lots of dead CAs, you need to perform AD cleanup from deads. They have no value by sitting in AD. Another thing is that when connecting to CAs I retrieve a lot of useful information, including service state.

**Comment by PatrickOnGit** [comment]
Hello Vadims

Thank you for clarification. So far I used only `Get-CertificationAuthority` and assumed but never checked `Connect-CertificationAuthority` would be an alias.

Suggesting using DNS as one option for name resolution was a bad option. Your point.

`directoryservices.activedirectory.domain.getcurrentdomain` is only available in AD. Instead of appending current users domain do a quick onelevel search in configuration context for PKI-Enrollment-Service object. This contains the dNSHostName property your looking for.
To connect a domain joined standalone CA we can still query global catalog for server name (CN) and retrieve the dnsHostName property. But the search has to use GC to get the computer within the forest. If the Standalone CA is not domain joined, well, it may or may not be in the same DNS realm than the user trying to connect. In fact,`Connect-CertificationAuthority` does not support credentials, connecting an unjoined standalone CA will only work locally. 

Best regards
Patrick

**Comment by Crypt32** [comment]
Thread wasn't updated for a long time.
