### ISSUE TITLE
Get-IssuedRequest enhancements proposal

### ISSUE THREAD

**Issue by PatrickOnGit** [PKISolutions/PSPKI#87]
`Get-IssuedRequest` and related commands are missing some useful parameters and defaults.

**Suggesting sorting descending on RequestID**

Default sort order in ADCS database is ascending RequestID. When dealing with small databases it is inefficient to read all entries and sort using PowerShell, dealing with large databases this is impossible as the command always times out or has to return thousands of objects before results can be sorted.
 ```
 $RColumn = $CAView.GetColumnIndex($False, "RequestID")
 $CaView.SetRestriction($RColumn,[CVR.SEEK]::NONE,[CVR.SORT]::DESCEND,0)
```

**Suggestion to default limit to last 30 days**
When dealing with large amount of certificates, it would be helpful to retrieve only x amount of days. Though it it is possible to limit using -filter parameter, a parameter like -days with default of 30 would simplify the usage. Setting to 0 would allow retrieving without limits.
Having said this, the relevant date may differ between the queried table (Request.SubmittedWhen,Request.ResolvedWhen,Request.RevokedEffectiveWhen).
When considering adding this parameter, a hint should be displayed that the results are limited to x days.

**Suggestion add sort parameter**
-Descending PropertyName
-Ascending PropertyName

**Suggestion to add parameter to retrieve last request**
-lastRequest 
`certutil` supports "RequestId==$" to retrieve the last request. The current -filter parameter does not suppor this.
More PowerShell like would be a paramter like -lastRequest to get the last issued / failed / pending request.

**Comment by Crypt32** [comment]
I didn't implement sorting, because it is not supported for all columns. Only indexed columns with blittable (or convertible to integral) data types support sorting. This may be somewhat complex to users who are not much faimilar with CA database details. Only if I limit sorting by `RequestID` column (which will be hardcoded). I don't know how else I can fix potential usability issues.

> Suggestion to add parameter to retrieve last request

may be a good thing to add. Though, if sorting will be implemented, last request could be retrieved by using filters:
``` PowerShell
Get-IssuedRequest -CA $ca -Filter "RequestID -le $([int]::MaxValue)" -PageSize 1 -Descending
```
or something like this. BTW, didn't know that certutil has this syntax.

> Suggestion to default limit to last 30 days

this won't solve timeout issues in case when database is bloated in a given period. I suggest to use `-PageSize` parameter to limit the number of output rows. In order to dump large database without getting timeout, I suggest to do it in chunks:

``` PowerShell
$Page = 1
$PageSize = 10000 # Maybe it can be 50k, or even 100k. Need to profile each particular instance. 10k is just a safe example
do {
    $i = 0
    Get-IssuedRequest -CA $ca -Page $Page -PageSize $PageSize | ForEach-Object {
        $i++
        $_
    }
    $Page++
} while ($i -eq $PageSize)
```
Using this technique you can dump any CA database pretty efficiently (in terms of resources and execution time).

**Comment by PatrickOnGit** [comment]
> I didn't implement sorting, because it is not supported for all columns. 
This could be solved by defining enumerations of properties which support sorting like `-Desc <EnumSort-AbleProperty>`. This way the user can only select  sort-able properties. As sorting only works for one property, it shouldn't be too complex. AND for those who don't understand, they can still use PowerShell and wait longer ;-)

>  Though, if sorting will be implemented, last request could be retrieved by using filters
> 'Get-IssuedRequest -CA $ca -Filter "RequestID -le $([int]::MaxValue)" -PageSize 1 -Descending'

True, but more complex than 
'Get-IssuedRequest -CA $ca -LastRequest'

> this won't solve timeout issues in case when database is bloated in a given period. 
You are right. I implemented this in an older "PowerShell" only PSPKI lokal fork as paging wasn't implemented. So paging is the better approach.

**Comment by Crypt32** [comment]
> This could be solved by defining enumerations of properties which support sorting like -Desc <EnumSort-AbleProperty>.

seems reasonable. Can we move this into separate issue item?

> True, but more complex than

I don't see much value in this. If previous item will be implemented, then this syntax could be used:

``` PowerShell
Get-IssuedRequest -CA $ca -OrderByDescending RequestID -PageSize 1
```
And no need to implement extra "-FirstRequest" and "-LastRequest" or whatever else.

> So paging is the better approach.

it is technically possible for me to wrap existing code in loops, so I internally query CA database in chunks, but this will be incompatible with sorting, because I'm not sure how the query is executed internally. If sorting performed only on result set, this may be fine, but if it requires whole database sorting, this will negatively affect query performance. For now, I'm not sure if it is common to dump entire database. Of course, there are rare cases when you need this, but writing a tiny loop for this particular operation is not a huge overhead.

From all three enhancement requests I agree on sorting only.

**Comment by PatrickOnGit** [comment]
one out of three, that sounds good to me :-)

**Comment by Crypt32** [comment]
Features are selected and placed in separate working items.
