### ISSUE TITLE
Problem with Certificate Templates

### ISSUE THREAD

**Issue by mcdonamw** [PKISolutions/PSPKI#90]
I'm having problems getting the actual Certificate Template for all of my certs because the CertificateTemplate and CertificateTemplateOID properties are not consistent for all of my certs, making it impossible to pipe the information to Get-CertificateTemplate in order to spit out the Display Name of the template. 

For example, I have two templates, for purposes of comparison here, who's display names are as follows in the CA MMC snapin.  

- Basic EFS

- Website 2year 2048key

When I run Get-IssuedRequests for certs coming from those templates, I get the following:

```Powershell
Get-CertificationAuthority myserver | Get-IssuedRequest -Properties *  | ? {$_.RequestID -eq 845 -OR $_.RequestID -eq 852} | select RequestID,CertificateTemplate,CertificateTemplateOID
     
RequestID CertificateTemplate                                                                 CertificateTemplateOid
--------- -------------------                                                                 ----------------------
      845 EFS                                                                                 EFS
      852 1.3.6.1.4.1.311.21.8.13663925.4144028.16007601.1195957.8777719.208.16345555.1589748 Website 2year 2048key (1.3.6.1.4.1.311.21.8.13663925.4144028.16007601.1195957.8777719.208.16345555.1589748)

```

As you can see, the CertificateTemplate property shows "EFS" for one template, which I would expect, but the other shows "1.3.6.1.4.1.311.21.8.13663925.4144028.16007601.1195957.8777719.208.16345555.1589748" which is actually the OID of the cert.  "EFS" is *not* the OID for first cert.

The other property, CertificateTemplateOID, I would expect it to actually contain the OID of the cert, but it doesn't.  It contains the same information for the first cert as the previous property, but the second cert is a combination of the actual DisplayName I want PLUS the OID.

I do not understand this behavior.  Also, this inconsistency makes it impossible for me to do a calculated column by piping out to Get-CertificateAuthority and pulling the DisplayName property of each template.  I can pipe out the CertificateTemplate successfully, but only for the second cert above.  The first cert shows a blank value for DisplayName because "EFS" is not a valid OID.  

```Powershell
Get-CertificationAuthority myserver | Get-IssuedRequest -Properties *  | ? {$_.RequestID -eq 852 -OR $_.RequestID -eq 845} | select RequestID,@{N="Template";E={(Get-CertificateTemplate -OID $_.certificatetemplate).DisplayName}} 

RequestID Template
--------- --------
      845
      852 Website 2year 2048key

```

**Comment by mcdonamw** [comment]
Odd the code block is not formatting properly.  Sorry.

**Comment by Crypt32** [comment]
`CertificateTemplate` property is the copy of apporpiate column in CA database. Sometimes (for v1 templates), it stores template name, sometimes (for v2+ templates), OID value associated with template. It is just about how CA stores template name in database.

`CertificateTemplateOid` stores an `Oid` object of the string stored in `CertificateTemplate` property. I see this behavior enough consistent and by design.

> "1.3.6.1.4.1.311.21.8.13663925.4144028.16007601.1195957.8777719.208.16345555.1589748" which is actually the OID of the cert. "EFS" is not the OID for first cert.

this is how [Oid](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.oid?view=netframework-4.8) class and custom formatter works. If OID is resolved, then [FriendlyName](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.oid.friendlyname?view=netframework-4.8#System_Security_Cryptography_Oid_FriendlyName) is populated. If OID cannot be resolved, an unresolved value (which can be either, friendly name or dot-numeric value) is set to [Value](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.oid.value?view=netframework-4.8#System_Security_Cryptography_Oid_Value) property.

That is, because of behavior of [Oid](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.oid?view=netframework-4.8) class, there is no guarantee that `Value` property always contains dot-numerical OID value. If OID cannot be resolved, then input value is copied to `Value` property.

**Comment by mcdonamw** [comment]
Hmm.  So how do I reliably get the name of the template that I need?  If the MMC snapin can show these names, I would imagine I should be able to get the same easily with your cmdlet.

**Comment by Crypt32** [comment]
Ok, seems like I need to add some constant mappings between V1 templates and their OIDs based on [MS-CRTD].

**Comment by mcdonamw** [comment]
Ah ok.  Just making sure it's not something I'm doing wrong.  Thank you so much.  Look forward to the enhancement if/when it comes.

**Comment by Crypt32** [comment]
Unfortunately, there is no 1:1 mapping between V1 templates and their OIDs. Unfortunately, I can't fix this in a current implementation.

**Comment by itsvivs** [comment]
Hello Crypt32 - do u have a solution to this issue?

**Comment by Crypt32** [comment]
Please, open your own issue item with your specific details.
