### ISSUE TITLE
Terminating error thrown for malformed pattern

### ISSUE THREAD

**Issue by hmiller10** [PKISolutions/PSPKI#95]
![ModuleV3 4 2 0_terminating_error](https://user-images.githubusercontent.com/8051832/68688727-ebc1b400-0534-11ea-9c92-9610eea4d228.png)
In module version 3.2.6 when a request was made using Get-IssuedRequest -RequestID a malformed search pattern against a database where the certificate did not exist would write warning message to the PS console.

In module version 3.4.2.0 that same request throws a terminating error. Even though the request and search pattern is valid when connecting to and searching the CA database where the certificate resides.

Please revert this behavior to act as it did in version 3.2.6 so that a request will succeed even though the database does not contain the certificate.
![Modulev3 2 6_warning_message](https://user-images.githubusercontent.com/8051832/68688743-efedd180-0534-11ea-8dca-cbb0d2276d87.png)

**Comment by Crypt32** [comment]
Warnings were removed from most commands to provide more consistent and reliable behavior. Warnings with silent fail had poor experience, because you can't know if the command failed or succeeded in unattended scenarios. Therefore, if some critical part is incorrect, I throw exception to notify caller that things went wrong instead of allowing of getting unexpected results. With terminating errors, caller may detect them using try/catch clauses.

**Comment by hmiller10** [comment]
Vadims,

I added some try/catch clauses to the script that does revocations, however the same error
'C:\temp\Revoke-PKICertificate.ps1 : Malformed filter: 'RequestID -eq ': At C:\Program
Files\WindowsPowerShell\Modules\PSPKI\3.4.2.0\Server\Get-RequestRow.ps1:17 char:17
+                 throw "Malformed filter: '$line'"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Revoke-PKICertificate.ps1 -SerialNumber '5700246f5e5228271cca5ae6d5 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Revoke-PKICertificate.ps1' 

is still thrown. It's only being thrown from CA where the certificate does not reside. It works fine on the CA where the certificate is actually located.


Can anything be done with the code to make it perhaps less threatening to an end user who did not write the script or doesn't understand PowerShell error handling?


Attached is a copy of the script I am referencing.


[Revoke-PKICertificate.ps1.txt](https://github.com/PKISolutions/PSPKI/files/3847227/Revoke-PKICertificate.ps1.txt)

**Comment by Crypt32** [comment]
The issue is with your code, in the `if ($Certs.Count -eq 1)` and `else` clause.

If one item is returned, then you go down the road and do the stuff. Everything looks legit (more or less. Though, I don't like statements like `$RequestID = $Certs.RequestID` since `$Certs` is marked with `[Array]`. Instead, I would explicitly use `$RequestID = $Certs[0].RequestID` indexer.

Your `else` clause assumes that `Get-IssuedRequest` returned more than one request row. However, `foreach-object` loop inside `else` clause will be executed even if no rows were returned. You can easily check this:

``` PowerShell
$null | %{Write-Host "I'm here"}
```
it will execute. So you have to explicitly check if any row was returned. I would do it this way:

``` PowerShell
if ($Certs.Count -gt 0) {
    # put entire code from existing ELSE clause
}
```
In addition, I would move `Get-CertificationAuthority -ComputerName $CA | Publish-CRL -DeltaOnly` line out of `foreach` loop. Process all entries in the loop and then publish new CRLs.

Another line:
``` PowerShell
$CA = $Certs = $RequestID = $null
```
I would replace with
``` PowerShell
Remove-Variable CA, Certs, RequestID
